### ISSUE TITLE
Issues with Stitch Outbrain integration records

### ISSUE THREAD

**Issue by robertotraberIG** [singer-io/tap-outbrain#8] opened 2018-02-20 20:26 UTC
Hello, I'm having some missing records since the 14th of February (2018) in some campaigns of my Outbrain integration on Stitch, sincerely I have no idea the reason of what's happening. The Stitch support guys told me to raise an issue for this since they found no abnormal activity. Does anyone noticed some extrange activity with data sync from the Outbrain integration from stitch this last days? I'm sorry for not giving any further information, If someone has an idea of what would be going on please let me know and maybe I could give more informations about the problem.

Thanks in advance.

**Comment by briansloane** [comment] 2018-02-21 19:06
@robertotraberIG Can you provide some more information about what data is missing?

Notably from the [README](https://github.com/singer-io/tap-outbrain) on the repo:

> Campaign pagination is not implemented -- this integration pulls incomplete data if more than 100 campaigns exist.

Could this be the cause of your missing data?

**Comment by robertotraberIG** [comment] 2018-02-21 19:41
Hello @briansloane thank you for your response, the thing is that my Outbrain integration in stitch is only bringing the first 25 campaigns ordered by creation date (as i can see). Those campaigns it's bringing they're inactive right now and the've been inactive since a long time ago. Considering the pagination issue is there any possibility that the integration only delivers the actual active campaigns and also is there any possibility this "limit" of 25 campaigns be setted at 100 campaigns or be unlimited?.

Thank you,

**Comment by briansloane** [comment] 2018-02-23 14:56
We just did some testing of the version before and after that latest commit and they both seem to return the same amount of campaigns. 

I dug into the API docs a bit further and noticed that the campaigns endpoint actually has a default limit of 25. I am unable to find any changelog for the API but it is possible that Outbrain recently changed this default. Here are the docs to the specific campaigns endpoint for reference:

https://amplifyv01.docs.apiary.io/#reference/campaigns/campaigns-collection-via-marketer/list-all-campaigns-associated-with-a-marketer

I think the resolution for this will be to increase the default to the max of 50 and also implement pagination so that we can get more than 50.

**Comment by robertotraberIG** [comment] 2018-02-23 15:36
Hello Brian, thank you for your reply, I perfectly understand what the resolution for this would be, but, is there any possibility to change right now this limit to 50 and furthermore set the API to only bring the non archieved campaigns?. Also, when do you think this changes on the Outbrain Tap will be commited?
Thanks.

**Comment by timvisher** [comment] 2018-07-23 20:39
Closed via https://github.com/singer-io/tap-outbrain/commit/e98f69690b5929c4675e7d45625e4fb87076a081

**Closed by timvisher** 2018-07-23 20:39 UTC
